DROP TABLE IF EXISTS BEER;

CREATE TABLE BEER (
ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255),
DESCRIPTION VARCHAR(MAX),
MASH_TEMP BINARY(255)
);

ALTER TABLE BEER ADD CONSTRAINT beer_name UNIQUE (name);